### ISSUE TITLE
Add namespace value to allow override of release namespace in enterprise-operator chart

### ISSUE THREAD

**Issue by jstudler** [mongodb/helm-charts#112]
As discussed with @priyolahiri opening this issue here on Github.

Due to our chart/subchart and Argo CD structure, we deploy the enterprise-operator chart in the default namespace while the resources should be deployed to a different namespace (e.g. mongodb-management). We cannot change the release namespace in our setup but would still like to use your the official enterprise-operator chart provided by MongoDB. This feature request is a proposal to implement a backwards compatible way to satisfy our needs.

Request:

- Add an optional  value "namespace" to the helm chart which will act as override for the Namespace.
- If the value is set, override the namespace in all enterprise-operator templates (e.g. https://github.com/mongodb/helm-charts/blob/main/charts/enterprise-operator/templates/operator.yaml#L6 ).

Required change to metadata.namespace of the template manifests:

`  namespace: {{- if .Values.namespace }}{{ .Values.namespace }}{{ else }}{{ .Release.Namespace }}{{ end }}`

**Comment by rodrigovalin** [comment]
Hello @jstudler

Thanks for reporting this issue. Let me know if I understand this correctly.

You want to install the Operator in `namespace/default` while creating databases in a different namespace `namespace/mongodb-management`, and having the Operator watch over those resources in `mongodb-management`.

If that's the scenario you are looking after, then you can do this by passing the `operator.watchNamespace` configuration to `helm install` like

    helm install enterprise-operator mongodb/enterprise-operator --namespace default --set operator.watchNamespace="mongodb-management"

Helm install install the Operator Pod in the `default` namespace, and will configure it to watch over resources in `mongodb-management` namespace.

Let me know if this works for you.

**Comment by priyolahiri** [comment]
@jstudler I am thinking whether you would want to maintain your own fork of the helm charts repo for stuff like this.

**Comment by jstudler** [comment]
@priyolahiri we would rather not. We're exactly trying to avoid this. Do you think implementing this in your helm chart would be a problem? I think it can be implemented without breaking the existing behaviour.

**Comment by acidicX** [comment]
I've also recently stumbled upon this, same issue if you try to deploy the operator into another namespace with a Flux CD setup. What @jstudler suggests would fix the issue and, as far as I can see, would not break anything on existing setups :+1:

@priyolahiri maintaing a fork for something that most of the "enterprise" charts already bring to the table seems overkill, especially since this seems to be quite a straight forward fix...

**Comment by priyolahiri** [comment]
@jstudler and @acidicX putting this up in the dev queue. will have an update on this soon.

**Comment by mircea-cosbuc** [comment]
Hi @jstudler and @acidicX ! While I agree with you the solution to provide an operator namespace value wouldn't affect the functionality provided by the chart currently, this is not a common best practice (e.g.): 
- https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
- https://github.com/elastic/helm-charts/tree/main/elasticsearch

If I understand your use-case correctly, it is the same one described in this issue: https://github.com/helm/helm/issues/5358 and the functionality is not supported in vanilla helm. Are tools like https://github.com/Praqma/helmsman and https://github.com/helmfile/helmfile easy to fit in your workflow instead? 

Thank you for your patience with this. While we have a solution similar to the Jenkins helm chart https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml , we'd like to better understand your usecase to make sure this wouldn't make the chart responsible for too many configuration variants.

**Comment by jstudler** [comment]
Hi @mircea-cosbuc 
I agree that usually helm charts do not have namespace override values. But some of them do have them as mentioned in the helm github issue you've linked.
Falling back to tools like helmsman or helmfile is not the solution we aim for as we'd like to stick to native tooling for our Argo CD stack. Therefore, our fallback at the time being is that we have a separate helm chart for the enterprise-operator.

**Comment by mircea-cosbuc** [comment]
That makes sense, thank you for the follow-up!

**Comment by mircea-cosbuc** [comment]
Hi @jstudler , the latest release of the enterprise operator allows for overriding the operator namespace using the `operator.namespace` value override. Closing the issue for now, please follow up if encountering any issues.
