### ISSUE TITLE
Unable to install community operator through Helm

### ISSUE THREAD

**Issue by Reinkaos** [mongodb/helm-charts#115]
Hey,

I have been unable to install the mongodb operator through Helm, when I run:

```
helm install mongodb-operator mongodb-helm-charts/community-operator --version 0.7.2 --namespace staging
```

I get:

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"]
```

Any help is much appreciated!

Thanks,

**Comment by priyolahiri** [comment]
Do you have cert-manager installed on the cluster?

**Comment by Reinkaos** [comment]
Hey @priyolahiri, thanks for your reply! No I don't have cert manager installed on the cluster. I will try and skip it :).

**Comment by Reinkaos** [comment]
Great that fixes it, thank you!
