### ISSUE TITLE
watchnamespace doesn't works like it should in the community chart

### ISSUE THREAD

**Issue by maxisam** [mongodb/helm-charts#134]
**What did you do to encounter the bug?**
**What did you expect?**
watchnamespace should handle a list of namespaces like in the enterprise version

https://github.com/mongodb/helm-charts/blob/61b3c94809e8fba23114833733c5b198bd2a7fba/charts/enterprise-operator/templates/operator-roles.yaml#L17

**What happened instead?**
A clear and concise description of what happened instead

community version doesn't work 

```
  | 2 | kind: Role
  | 3 | metadata:
  | 4 | labels:
  | 5 | argocd.argoproj.io/instance: mongodb-production
  | 6 | name: mongodb-kubernetes-operator
  | 7 | namespace: 'web-app-db,dev'

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**
Add any other context about the problem here.

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by bit-herder** [comment]
it would be great if this got fixed
