### ISSUE TITLE
community-operator: crds are not installed in time for consumption 

### ISSUE THREAD

**Issue by Morriz** [mongodb/helm-charts#143]
**What did you do to encounter the bug?**
1. install the operator like this:

```
helm install community-operator mongodb/community-operator --namespace mongodb-operator --create-namespace --set operator.watchNamespace=mongodb --set createResource=true,tls.enabled=true
```

**What did you expect?**
No issues

**What happened instead?**
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "MongoDBCommunity" in version "mongodbcommunity.mongodb.com/v1"
```

**Kubernetes Cluster Information**
 - Distribution: Digitial Ocean
 - Version: 1.22

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by Morriz** [comment]
I also see that crds are packaged as regular resources (under `templates/`) in a dependency chart, which is going against helm v3 best practices. It would be safe to publish them directly in a `crds/` folder in the chart.

**Comment by Morriz** [comment]
More issues:
- `.Values.namespace` isn't found in `values.yaml`, which leads to errors when turning on tls

**Comment by irajdeep** [comment]
Hello @Morriz 

Thanks for creating the issue.  I think you have already figured this out based on the details in the linked ticket, but for now, set `createResource=true` only if the CRD has been installed. 

We will add this to our documentation and possibly explore if we can improve this user experience.

**Comment by irajdeep** [comment]
> but I recommend to follow best practices and go through the chart with a comb to catch all culprits.

We understand. This is something we will look into.

As far as the problem that you've mentioned in this issue. Our recommendation, for now, is to install the operator and the corresponding CRDs in the first step and there after creating the customResource with the helm commands.

**Comment by lagivan** [comment]
I'm facing a very similar issue, getting the following error:

```
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "mongodb-replica-set" namespace: "mongodb" from "": no matches for kind "MongoDBCommunity" in version "mongodbcommunity.mongodb.com/v1"
ensure CRDs are installed first
```

In order to simplify installation I actually like to create resource with helm, i.e. I have `createResource=true`.

My workaround is to install CRD's operator first and only then install the main operator:

```
helm upgrade --install community-operator-crds mongodb/community-operator-crds \
  --namespace mongodb \
  --create-namespace \
  --version v0.7.5
  
helm upgrade --install community-operator mongodb/community-operator \
  --namespace mongodb \
  --version v0.7.5 \
  --values=kubernetes-mas8/mongo/mongodb-conf.yaml
```

Of course, it would be great if crds were correctly installed automatically and no extra step was required.

**Comment by HoustonDad** [comment]
This issue is still occurring.
