### ISSUE TITLE
Mongodb community operator 0.7.7 gone

### ISSUE THREAD

**Issue by OldWarrior3000** [mongodb/helm-charts#204]
**What did you do to encounter the bug?**
We are deploying on our kubernetes environments via terraform. We just wanted to release an update of the mongodb k8s community operator and it stopped working. It seems like the helm chart is gone from the releases.

This is the error that I am getting.

![image](https://user-images.githubusercontent.com/22188752/215454221-39deeef0-75a4-463e-87be-78dc791011cb.png)

It was working an hour ago. Was there a recent change which deleted the release from the helm registry?

Thanks in advance

**What did you expect?**
Helm release 0.7.7 to be able to download.

**What happened instead?**
Helm terraform operator throws an error as it cannot find the release

**Kubernetes Cluster Information**
 - AWS EKS on AWS linux images
 - 1.23
 - public helm registry from  mongodb

**Comment by kjelljoakim** [comment]
Same here. Looks like [this](https://github.com/mongodb/helm-charts/commit/0e040f792add0f56d65c4bf932299dd4ff4e40ef) change references a releases that doesn't exist, [0.7.6](https://github.com/mongodb/helm-charts/releases/tag/community-operator-0.7.6) is the latest community operator release. 

I was able to to get it working by fixing the chart version to 0.7.6 as a workaround

**Comment by OldWarrior3000** [comment]
I can confirm it 0.7.6 is working.

**Comment by mircea-cosbuc** [comment]
Hi @OldWarrior3000 @kjelljoakim ,
Thank you for raising this issue! The `0.7.7` release of the community operator was pointing to the wrong operator image and we attempted an in-place fix which explains the temporary disappearance of the chart archive. It is back in place and a new release (0.7.8) was also completed and is currently available.
Please re-open the issue if you encounter additional problems with these two latest releases.
