### ISSUE TITLE
community-operator helm chart should support `extraManifests`

### ISSUE THREAD

**Issue by JunaidChaudry** [mongodb/helm-charts#213]
**Describe the Issue**

The community-operator helm chart should support `extraManifests`, which it doesn't as of right now. 

The new addition, is in alignment with many other opensource helm charts (e.g. [grafana](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/extra-manifests.yaml), prometheus, argo-cd, etc.), to support extra k8s manifests using the values files.
This allows the end user to add any additional files needed to support their helm deployment. A nice use case now a days is to mount secrets on the fly by leveraging the [Secrets Store CSI Driver.](https://github.com/kubernetes-sigs/secrets-store-csi-driver). 

With the `community-operator` helm chart, the `extraObjects` feature can be useful to create the kubernetes secret to store the password for `MongoDBCommunity` users. 

Chart Name
community-operator

PR Feature
https://github.com/mongodb/helm-charts/pull/212

**Comment by Jamison1** [comment]
This feature may also be useful for replicas, nodeSelector, nodeAffinity and tolerations.  When defining which node-roles the pods can be deployed on.  

For example, although you can use podAntiAffinity, nodeSelector and tolerations in the MongoBCommunity file, this only impacts mongodb pods and not the mongodb-kubernetes-operator pod.  

Enabling replicas, nodeSelector, nodeAffinity and tolerations for the operator pod during the helm install process could be useful.

**Comment by adecchi-2inno** [comment]
I need to setup tolerations . Is it resolved ?
