### ISSUE TITLE
helm charts install enterprise 1.20.1 failed

### ISSUE THREAD

**Issue by KevenNock** [mongodb/helm-charts#230]
mongodb-system   4m14s       Normal   BackOff   pod/mongodb-enterprise-operator-5c98c964c-nrhjd   Back-off pulling image "quay.io/mongodb/mongodb-enterprise-operator:1.20.1"

it seems image quay.io/mongodb/mongodb-enterprise-operator:1.20.1 no exits

**Comment by maboehm** [comment]
`quay.io/mongodb/mongodb-enterprise-operator-ubi:1.20.1` exists - not sure if the old path is supposed to be missing. 
seems like https://github.com/mongodb/helm-charts/blob/main/charts/enterprise-operator/values.yaml#L15 needs to be updated here

**Comment by mircea-cosbuc** [comment]
Hi @KevenNock @maboehm , thank you for raising this issue. We stopped building ubuntu images for the operator which the default values.yaml was referring to in the latest release of the operator. The chart has been fixed to correctly refer to the `-ubi` image. Please re-open in case you're still encountering the issue.
