### ISSUE TITLE
k8s Enterprice operator with UBI based image

### ISSUE THREAD

**Issue by hariapollo** [mongodb/helm-charts#232]
**What did you do to encounter the bug?**

**What did you expect?**
I am expecting to deploy ops manager K8S enterprice operator with UBI based image. However in charts its still ubuntu based image [image](https://github.com/mongodb/helm-charts/blob/50bd0ec1a6a148a63cb98e3f4d7377d111a0f1c8/charts/enterprise-operator/values.yaml#L12). Is it going to change soon?. All other are with UBI based, only operator is not changed. Any reason for that?

**What happened instead?**
A clear and concise description of what happened instead

**Screenshots**

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by mircea-cosbuc** [comment]
Hi @hariapollo , the `1.20.1` release of the enterprise operator has been fixed to use the `-ubi` image by default. We are currently only releasing `-ubi` images for the new versions of the operator.
