### ISSUE TITLE
community-operator should support `priorityClassName`

### ISSUE THREAD

**Issue by siegenthalerroger** [mongodb/helm-charts#243]
The community operator should allow setting a `priorityClassName` for the operator deployment from values.yaml.

This aligns with other operators and enables the correct usage of priority classes within k8s.

**Comment by siegenthalerroger** [comment]
This is still relevant

**Comment by siegenthalerroger** [comment]
This is still relevant

**Comment by vramperez** [comment]
I totally agree, it is necessary.

**Comment by siegenthalerroger** [comment]
@nammn I see the pull request was merged, would it be possible to get a patch or minor release of the community-operator chart to make the functionality available?

**Comment by vramperez** [comment]
That would be great!

**Comment by nammn** [comment]
@siegenthalerroger @vramperez there are plans for a release in around 2-3 weeks

**Comment by nammn** [comment]
@vramperez @siegenthalerroger there is a release planned in around 2-3 weeks.

**Comment by vramperez** [comment]
@nammn I see that a release of the community operator including this change has not been released yet, any news on when the release will be released?

**Comment by siegenthalerroger** [comment]
This has been releasesd
