### ISSUE TITLE
objectDeletionProtection is not switch off 

### ISSUE THREAD

**Issue by noamgreen** [mongodb/helm-charts#268]
**What did you do to encounter the bug?**

I am using helm chart  "mongodb-atlas-operator" from "https://mongodb.github.io/helm-charts" 
 var : 1.9.1 ( last ). 

i see you add new values 

'''  yaml 
objectDeletionProtection: true
subobjectDeletionProtection: true
'''

when i run the service i am seeing this error 
 '''
flag provided but not defined: -object-deletion-protection
''''

from the Service  out log 

at that point i didn't  see where i need to " defined " a list or ? not clear and you need to add more info 
then i switched it off 
and i see in the service log same error  "flag provided but not defined: -object-deletion-protection"

'''
    Command:
      /manager
    Args:
      --atlas-domain=https://cloud.mongodb.com/
      --health-probe-bind-address=:8081
      --metrics-bind-address=:8080
      **--object-deletion-protection=false
      --subobject-deletion-protection=false**
      --leader-elect
'''

working on 
EKS : 1.24 

so i think you have a bug or i am not sure what am i missing in any case i am going back to 1.9.0

pls advice
Thanks

**Comment by blochsbek** [comment]
Also running into this as an issue.

**Comment by josvazg** [comment]
Seems some changes for an upcoming version had made it to that release 1.9.1 by mistake.
This only affects the helm chart so, while we work on a new fixed release of the chart, I would recommend to use the 1.9.0 chart but bump the image version to 1.9.1 in the Chart.yaml
