### ISSUE TITLE
[community-operator] Add support of nodeSelector and tolerations for the operator pod

### ISSUE THREAD

**Issue by Privatecoder** [mongodb/helm-charts#308]
Currently (chart `community-operator v0.9.0`) the `nodeSelector` and `tolerations` for the operator pod cannot be set and therefore the operator cannot be scheduled on `tainted` nodes

We should implement that in the community-operator chart in order to support the customization of these parameters.

**Comment by MaesterZ** [comment]
Can we reopen this issue? I will create a PR in a few.
