### ISSUE TITLE
Missing Version Compatibility Table for MongoDB Operator

### ISSUE THREAD

**Issue by shubham-cmyk** [mongodb/helm-charts#346]
ensure compatibility with the specific MongoDB version being used.

**Comment by helderjs** [comment]
Hi @shubham-cmyk!
First, sorry for taking such a long time to reply, and thank you for raising awareness about this.
However, with such a brief description, it is hard for us to visualize how this is causing you a problem and what you would expect
as a solution. For now, we will close the issue and we expect you to open a new one with a more detailed explanation so we can triage and look at how we can improve the charts and solve your issue.
