### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by rajivml** [mongodb/helm-charts#36]
HI, 

Do you have better documentation for enterprises to follow. The quick start documentation just assumes that you are in the right folder and appropriate environment variables are created before triggering the commands documented.

And for enterprise installs, is it the right helm chart that has to be used ?

https://github.com/mongodb/helm-charts/tree/main/charts

**Comment by jasonmimick** [comment]
Hello @rajivml -

MongoDB will be rolling out additional updates to this repo and our official docs to cover the Enterprise and all the operators. Thanks for your patience -
