### ISSUE TITLE
Wrong values in charts for backups

### ISSUE THREAD

**Issue by MartinCanovas** [mongodb/helm-charts#38]
According to the [MongoDB Kubernetes](https://docs.mongodb.com/kubernetes-operator/v1.11/reference/k8s-operator-specification/#spec.backup.mode) documentation, the values on the helm charts are incorrect and won't work.

`backup:
     enabled: {{ .Values.backup }}`

should be:

`backup:
     mode: {{ .Values.backup }}`

and in values **"backup: false"** should be **"backup: disabled"**

**Comment by jasonmimick** [comment]
Hi @MartinCanovas -

Thanks for reporting this. We are planning to add an official chart for Enterprise DB repl sets in the near future; you can find a example for configuring this setting here in the meantime: https://github.com/mongodb/mongodb-enterprise-kubernetes/blob/master/samples/mongodb/backup/replica-set-backup.yaml
