### ISSUE TITLE
Add of labels or annotations

### ISSUE THREAD

**Issue by EricPE69** [mongodb/helm-charts#52]
Th chart should support the ability to add labels and/or annotations to the pods

**Comment by jasonmimick** [comment]
Hi @EricPE69 and @kwill4026 -

Could you please elaborate on this request? We have a number of charts in the repo and do support some annotations.

Thanks,
Jason

**Comment by kwill4026** [comment]
Well for my case I would like for a 3 node replicaset to be spun up with labels denoting the primary and the 2 secondaries.
