### ISSUE TITLE
Chart release is broken

### ISSUE THREAD

**Issue by Starefossen** [mongodb/helm-charts#70]
Looks like the chart release action is broken: https://github.com/mongodb/helm-charts/actions/workflows/main.yml

The new community-operator chart is missing from the index.

**Comment by fractal1977** [comment]
I second that...
community-operator chart is no more available for our K8s app catalog.
pls fix index

**Comment by Starefossen** [comment]
@rodrigovalin any chance we can get this fixed?

**Comment by rodrigovalin** [comment]
Hello @Starefossen, @fractal1977

Thanks for reporting. As you probably know by now, we have been moving things around in this repo to make it the canonical source repository for all MongoDB Helm charts. At the same time, we want to improve the overall quality of our Operators, specially regarding to docs and to provide a consistent behaviour across all of them.

The _Community operator_ has changed name, but this was a mistake on our side. You can find it as:

`mongodb/mongodb/mongodb-kubernetes-operator` and the current version is 0.7.1.

Be aware that this should change its name to the original name that you are expecting `community-operator`.

Please let me know if this solve your problems for now, we should have a definitive solution soon.

**Comment by rodrigovalin** [comment]
The Community Chart has been renamed back to `mongodb/community-operator`.

Thanks for reporting this issue!
