### ISSUE TITLE
Update to version 0.6.0

### ISSUE THREAD

**Issue by jhill072** [mongodb/helm-charts#78]
When attempting to reference a project I had found that I am required to make the databaseuser in the same namespace as the project. As of app version 0.6.0 that is no longer necessary. I'm not aware of what else has changed as part of 0.6.0, but I'd like to at least point out the version is available for others.

Official release: https://github.com/mongodb/mongodb-atlas-kubernetes/releases/tag/v0.6.0

**Comment by jasonmimick** [comment]
Thanks @jhill072 -
We are working on a number of enhancements, including properly watching one, many, or all namespaces as we work towards a Beta and GA for the Operator next year. 
We will be making a release before the end of this calendar year to pickup all these bug fixes.
